# docker/dev/Dockerfile.backend
FROM python:3.11

# Указываем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем backend и ставим зависимости
COPY ../../backend /app
RUN pip install --no-cache-dir -r requirements.txt

# Запускаем FastAPI dev-сервер
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
