services:
  backend:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    env_file:
      - .env.dev
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/plain_dev

  frontend:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  